---
title: "Untitled"
author: "Justin Vanneste"
date: "4/11/2020"
output: html_document
---

# Introduction

The subject I choosed is biotechnology. Biotechnology is the use of science and technology on living organism. This branch of science has a lot of uses in a large number of different fields such as medicine, agriculture, industrial and so on. The goal of biotechnology is to find new tool for thoses branches. The selected articles are most of them about trying to develop particularities of certain microorganism and adapt for our using. This subject central aspect is the genetic modification in order to put the character of one organism in an other. In medicine, biotechnology is used to found new curre against deseases, to develop new medicine, and also to improve our immune system, etc. In agriculture it's used to accelerate the grow, height and quality of the plant, it's also used to make those plants more resistent at several environmental changes like the temperature, the pH or the need of water. In industries, it is used to increase the performance but also to find a less pollutive way to produce the needs of our modern society. So biotechnology is a very vast subject with the project of find how we could improve organism with our knowledge and technology.
